### ISSUE TITLE
Replace pacpy copied files with an import

### ISSUE THREAD

**Issue by parenthetical-e** [voytekresearch/pacmat#1]
Figure out pathing, if necessary.

If we _must_ copy code make sure it is contained in sub-folder so it can easily be synced with `pacpy` as that package evolves.

**Comment by srcole** [comment]
I can do this if we instruct whoever downloads this to put pacmat and pacpy in the same directory. Does that sound reasonable to you?

**Comment by srcole** [comment]
No special pathing is needed if pacpy is installed properly :D
